
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: name-tests-test
        args: [--django]
  - repo: http://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        args: [--strict, --implicit-reexport]
        additional_dependencies: [numpy, pandas, types-requests]
        exclude: ^(tests/)
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
